services:
  tasksdd:
    build:
      context: tasks/
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_URL=${REDIS_URL}
      - FOLDER_DATA=${FOLDER_DATA}
      - HOURLY_URL=${HOURLY_URL}
      - DAILY_URL=${DAILY_URL}
      - MONTHLY_URL=${MONTHLY_URL}
    networks:
      phen-net:
        aliases:
          - transform-phen-net
    tty: true
    stdin_open: true
    volumes:
      - "./tasks:/app"
      - "${PATH_TO_CACHE}:/app/cache/"

networks:
  phen-net:
    name: phen-net
    external: true
      
  
